# Generated by Django 3.0.7 on 2021-08-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pizza_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza', models.CharField(choices=[('pizza1', 'pizzaone'), ('pizza2', 'pizzatwo'), ('pizza3', 'pizzathree')], max_length=50)),
            ],
        ),
    ]
