# Generated by Django 3.0.7 on 2021-08-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza_type',
            name='price',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pizza_type',
            name='size',
            field=models.CharField(choices=[('10 inche', '10 inche'), ('12 inche', '12 inche'), ('14 inche', '14 inche'), ('16 inche', '16 inche'), ('18 inche', '18 inche')], default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pizza_type',
            name='topping',
            field=models.CharField(choices=[('potato', 'potato'), ('broccoli', 'broccoli'), ('eggplant', 'eggplant'), ('mushroom', 'mushroom'), ('black olives', 'black olives'), ('fresh garlic', 'fresh garlic'), ('onion', 'onion'), ('tomato', 'tomato')], default=' ', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pizza_type',
            name='pizza',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Square', 'Square'), ('Marol', 'Marol'), ('Farmhouse', 'Farmhouse')], max_length=50),
        ),
    ]
